# Generated by Django 4.1.3 on 2022-11-16 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=8, null=True)),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(max_length=50, null=True, verbose_name="Фамилия"),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Ник")),
                ("password", models.CharField(max_length=50, verbose_name="Пароль")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Пользователь"),
                            ("moderator", "Модератор"),
                            ("admin", "Админ"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                ("age", models.SmallIntegerField()),
                ("location", models.ManyToManyField(to="ads.location")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Объявление")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Фото"
                    ),
                ),
                ("is_published", models.BooleanField(verbose_name="Опубликовано")),
                (
                    "author",
                    models.ForeignKey(
                        max_length=100,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads.user",
                        verbose_name="Продавец",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads.cat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
